from .node           import Node
from jpype           import JClass
from numpy.typing    import NDArray, ArrayLike
from numpy           import int_, float_
from pathlib         import Path
from logging         import Logger
from collections.abc import Iterator
from typing          import Literal


log: Logger
modules: dict[str, str]


class Model:

    java: JClass

    def __init__(self, parent: JClass | Model): ...

    def __eq__(self, other: object) -> bool: ...

    def __truediv__(self, other: Node | str) -> Node: ...

    def __contains__(self, node: Node) -> bool: ...

    def __iter__(self) -> Iterator[Node]: ...

    def name(self) -> str: ...

    def file(self) -> Path: ...

    def version(self) -> str: ...

    def functions(self) -> list[str]: ...

    def components(self) -> list[str]: ...

    def geometries(self) -> list[str]: ...

    def selections(self) -> list[str]: ...

    def physics(self) -> list[str]: ...

    def multiphysics(self) -> list[str]: ...

    def materials(self) -> list[str]: ...

    def meshes(self) -> list[str]: ...

    def studies(self) -> list[str]: ...

    def solutions(self) -> list[str]: ...

    def datasets(self) -> list[str]: ...

    def plots(self) -> list[str]: ...

    def exports(self) -> list[str]: ...

    def modules(self) -> list[str]: ...

    def problems(self) -> list[dict[str, str | Node]]: ...

    def build(self, geometry: str | Node | None = None): ...

    def mesh(self, mesh: str | Node | None = None): ...

    def solve(self, study: str | Node | None = None): ...

    def inner(
        self,
        dataset: str | Node | None = None,
    ) -> tuple[NDArray[int_], NDArray[float_]]: ...

    def outer(
        self,
        dataset: str | Node | None = None,
    ) -> tuple[NDArray[int_], NDArray[float_]]: ...

    def evaluate(
        self,
        expression: str | list[str],
        unit:       str | list[str] | None = None,
        dataset:    str | Node | None = None,
        inner:
            Literal['first', 'last']
            | list[int] | NDArray[int_]
            | None
            = None,
        outer: int | int_ | None = None,
    ) -> NDArray[float_] | list[NDArray[float_]]: ...

    def rename(self, name: str): ...

    def parameter(
        self,
        name:        str,
        value:       str | int | float | complex | None = None,
        unit:        str = None,
        description: str = None,
        evaluate:    bool = ...,
    ) -> None | str | int | float | complex: ...

    def parameters(
        self,
        evaluate: bool = ...,
    ) -> dict[str, str | int | float | complex]: ...

    def description(self, name: str, text: str = None) -> str | None: ...

    def descriptions(self) -> dict[str, str]: ...

    def property(
        self,
        node: Node | str,
        name: str,
        value: Node | bool | float | str | Path | ArrayLike | None = None,
    ) -> (None | Node | bool | float | str | Path | ArrayLike): ...

    def properties(
        self,
        node: Node | str,
    ) -> dict[str, Node | bool | float | str | Path | ArrayLike]: ...

    def create(self, node: Node | str, *arguments: list[str]) -> Node: ...

    def remove(self, node: Node | str): ...

    def import_(self, node: Node | str, file: Path): ...

    def export(self, node: Node | str | None = None, file: Path = None): ...

    def clear(self): ...

    def reset(self): ...

    def save(self, path: Path = None, format: str = None): ...

    def features(self, physics: str) -> list[str]: ...

    def toggle(self, physics: str, feature: list[str], action: str = ...): ...

    def load(self, file: Path, interpolation: str): ...
